name: 'app-pipeline'
on:
  push:
  pull_request:
    types: [ opened, reopened ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest] # TODO: add 'windows-latest' support
    runs-on: ${{ matrix.platform }}
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v1

      - name: Cache go dependencies
        id: unit-cache-go-dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/go/pkg/mod
            .tmp/
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Install go dependencies
        if: steps.unit-cache-go-dependencies.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: Run Static Analyses
        run: make lint

      - name: Run Tests
        run: make test

  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.x'

      - uses: actions/checkout@v1

      - name: Cache go dependencies
        id: package-cache-go-dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/go/pkg/mod
            .tmp/
          key: ${{ runner.os }}-go-prod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-prod-

      - name: Install dependencies
        if: steps.package-cache-go-dependencies.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: Build snapshot artifacts
        run: make snapshot

      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: dist


  test-linux-artifacts:
    needs: [ build-artifacts ]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist

      - name: Test linux run
        run: make ci-test-linux-run

      - name: Test docker run
        run: make ci-plugs-out-test

  test-mac-artifacts:
    needs: [ build-artifacts ]
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: artifacts
          path: dist

      - name: Test darwin run
        run: make ci-test-mac-run

  release:
    needs: [ test, build-artifacts, test-linux-artifacts, test-mac-artifacts ] # TODO: add windows support
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.x'

      - uses: actions/checkout@v1

      - name: Cache go dependencies
        id: release-cache-go-dependencies
        uses: actions/cache@v1
        with:
          path: |
            ~/go/pkg/mod
            .tmp/
          key: ${{ runner.os }}-go-prod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-prod-

      - name: Install dependencies
        if: steps.release-cache-go-dependencies.outputs.cache-hit != 'true'
        run: make bootstrap

      - name: Publish GitHub release
        run: make ci-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
